name: effective_internship
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  crypto: ^3.0.2
  get: ^4.6.5
  carousel_slider: ^4.1.1
  palette_generator: ^0.3.3+2
  clippy_flutter: ^2.0.0-nullsafety.0
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.11
  path: ^1.8.1
  image_picker: ^0.7.2+1
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  drift_dev: ^2.2.0+1

flutter:

  uses-material-design: true
  assets:
    - assets/

